import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import '../../globals.css';

import { DM_Sans, DM_Mono } from 'next/font/google';

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans', weight: ['400', '500', '600'] });
const dmMono = DM_Mono({ subsets: ['latin'], variable: '--font-mono', weight: ['400'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className={`${dmSans.variable} ${dmMono.variable} h-full antialiased`}>
            <body className='min-h-full flex flex-col'>
                <NextIntlClientProvider>{children}</NextIntlClientProvider>
            </body>
        </html>
    );
}
